/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE produtoBaseService PLEASE EDIT ../produto.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Produto } from '../../domain/cashback_db/produto';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Produto.service.ts
 */

/*
 * SCHEMA DB Produto
 *
	{
		nome: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Industria: {
			type: Schema.ObjectId,
			ref : "Produto"
		},
	}
 *
 */
@Injectable()
export class ProdutoBaseService {

    contextUrl: string = environment.endpoint + '/produtos';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProdutoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Produto): Observable<Produto> {
        return this.http
            .post<Produto>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ProdutoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProdutoService.findByIndustria
    *   @description CRUD ACTION findByIndustria
    *   @param Objectid key Id of model to search for
    *
    */
    findByIndustria(id: string): Observable<Produto[]> {
        return this.http
            .get<Produto[]>(this.contextUrl + '/findByIndustria/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ProdutoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Produto> {
        return this.http
            .get<Produto>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProdutoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Produto[]> {
        return this.http
            .get<Produto[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ProdutoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Produto): Observable<Produto> {
        return this.http
            .post<Produto>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
