package com.cashback.db.cashback_db.dtos.infos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE IndustriaInfoDto PLEASE EDIT ../IndustriaInfo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the info of Industria object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;


public class IndustriaBaseInfo {
	
	private Long _id;
	// Attributes
    private String cnpj;
    private String codigoInterno;
    private String nomeFantasia;
    private String senhaBIopcional;
    private String urlFotoIndustriaopcional;
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}
	public String getCodigoInterno() {
		return codigoInterno;
	}

	public void setCodigoInterno(String codigoInterno) {
		this.codigoInterno = codigoInterno;
	}
	public String getNomeFantasia() {
		return nomeFantasia;
	}

	public void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}
	public String getSenhaBIopcional() {
		return senhaBIopcional;
	}

	public void setSenhaBIopcional(String senhaBIopcional) {
		this.senhaBIopcional = senhaBIopcional;
	}
	public String getUrlFotoIndustriaopcional() {
		return urlFotoIndustriaopcional;
	}

	public void setUrlFotoIndustriaopcional(String urlFotoIndustriaopcional) {
		this.urlFotoIndustriaopcional = urlFotoIndustriaopcional;
	}
}